### ISSUE TITLE
Winter theme -- Need to change the default color of the Link

### ISSUE THREAD

**Issue by eslam-gomaa** [langzhou/toy-theme-for-siyuan#2]
Hello,

The color for the link &  text are very similar, It would be better if they are different or even there is a line below the link

Thank you in advance

![image](https://user-images.githubusercontent.com/33789516/123502116-06816780-d64a-11eb-9b5c-63db6699dc7e.png)

**Comment by langzhou** [comment]
@eslam-gomaa 
I also noticed that, and modified it in Toy theme.

For Winter theme, you can edit the file `winter.css` in line 133, change the link color what you want, such as:

```
--b3-protyle-inline-link-color:        #25789e; /* link color */
```

**Comment by eslam-gomaa** [comment]
Thank you @langzhou

**Comment by eslam-gomaa** [comment]
@langzhou 

DId as you said, but still not changed 

![image](https://user-images.githubusercontent.com/33789516/123618383-70477000-d808-11eb-8290-7f2b62bac550.png)

---

![image](https://user-images.githubusercontent.com/33789516/123618477-86edc700-d808-11eb-9031-38aa1f79b916.png)
