### ISSUE TITLE
Tonight theme (suggestion)

### ISSUE THREAD

**Issue by eslam-gomaa** [langzhou/toy-theme-for-siyuan#3]
Regarding these highlight colors, the default behavior is to keep the font color to white (which is not very readable)
I think it's gonaa be better if the font is displayed in black (Only in the Tonight theme, so that it doesn't conflict with other "light themes" like winter)

![image](https://user-images.githubusercontent.com/33789516/124115858-91a99580-da6e-11eb-8392-80fe8d63c7f3.png)

![image](https://user-images.githubusercontent.com/33789516/124115897-9e2dee00-da6e-11eb-85b1-633bc334db85.png)

**Comment by langzhou** [comment]
thanks for your suggestion. I've updated it in github. You can also edited it by yourself. Add these in tonight.css
```
strong[style*="background-color: var(--b3-font-background1)"],
strong[style*="background-color: var(--b3-font-background2)"],
strong[style*="background-color: var(--b3-font-background3)"],
strong[style*="background-color: var(--b3-font-background4)"],
strong[style*="background-color: var(--b3-font-background13)"]{
    color:#333 !important; 
}
```

**Comment by eslam-gomaa** [comment]
Thanks @langzhou 

I will edit them, but it's better if they are updated in the bazar theme (so that new updates don't override my changes)

![image](https://user-images.githubusercontent.com/33789516/124229830-7b531680-db0e-11eb-854e-92b6c4f1431d.png)

**Comment by langzhou** [comment]
> Thanks @langzhou
> 
> I will edit them, but it's better if they are updated in the bazar theme (so that new updates don't override my changes)
> 
> ![image](https://user-images.githubusercontent.com/33789516/124229830-7b531680-db0e-11eb-854e-92b6c4f1431d.png)

ok. I'll update in bazar
